BOLD_TXT=$(tput bold)
NORMAL_TXT=$(tput sgr0)
OPTIONS=(0 1 2 3 4 5 6 7 8 9 10 11 12 Q)

PROD_SERVER_ALIAS=PROD_SERVER_ALIAS

NGINX_REPO="NGINX_REPO_ON_DOCKER_HUB"
CLIENT_REPO="CLIENT_REPO_ON_DOCKER_HUB"
API_REPO="API_REPO_ON_DOCKER_HUB"