# Generated by Django 5.1.6 on 2025-08-09 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('process_pdf', 'Process PDF'), ('process_img', 'Process Image'), ('process_txt', 'Process Text'), ('process_audio', 'Process Audio'), ('translator', 'Translator')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Projects',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PDFProjectDetail',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_key', models.CharField(max_length=256, unique=True)),
                ('pdf_process_mode', models.CharField(choices=[('all', 'Process entire PDF'), ('specific', 'Process specific pages')], default='all', max_length=20)),
                ('pdf_pages_to_process', models.JSONField(blank=True, null=True)),
                ('user_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_details', to='processor.userproject')),
            ],
            options={
                'verbose_name_plural': 'PDF Project Details',
                'ordering': ('id',),
            },
        ),
    ]
