# Generated by Django 5.1.6 on 2025-08-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfprojectdetail',
            name='pdf_process_mode',
            field=models.CharField(blank=True, choices=[('all', 'Process entire PDF'), ('specific', 'Process specific pages')], max_length=20, null=True),
        ),
    ]
