# Generated by Django 5.1.6 on 2025-08-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_alter_pdfprojectdetail_pdf_process_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfprojectdetail',
            name='pdf_process_mode',
            field=models.CharField(choices=[('all', 'Process entire PDF'), ('specific', 'Process specific pages'), ('not_decided_yet', 'Not decided yet')], default='not_decided_yet', max_length=20),
        ),
    ]
